"""add user column provider to distinguish user sign up from native or google

Revision ID: 2139c2bcb991
Revises: 815d4cf50fbc
Create Date: 2021-05-20 23:06:13.272150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2139c2bcb991'
down_revision = '815d4cf50fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('provider', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'provider')
    # ### end Alembic commands ###
