"""user password to password_hash

Revision ID: e7d3123dabed
Revises: 333d31789f11
Create Date: 2021-05-14 21:51:51.787251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7d3123dabed'
down_revision = '333d31789f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=500), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=500), nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
