"""add travel_spot and Url and modified user length

Revision ID: fea397f99825
Revises: 5e07680b2642
Create Date: 2021-05-14 21:06:53.195975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea397f99825'
down_revision = '5e07680b2642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_spot',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('transport', sa.String(length=8000), nullable=True),
    sa.Column('category', sa.String(length=1000), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=1000), nullable=False),
    sa.Column('describe', sa.String(length=9000), nullable=False),
    sa.Column('mrt', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('url',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=8000), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['travel_spot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url')
    op.drop_table('travel_spot')
    # ### end Alembic commands ###
